#! /bin/sh

bspc monitor -d "www" "code" "dir" "txt" "chat" "vir" "msc" "vid" "gfx" "rec"

bspc config border_width			4
bspc config window_gap				10

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config focused_border_color	"#BD93F9"
bspc config normal_border_color		"#282A36"
bspc config active_border_color		"#8BE9FD"
bspc config presel_feedback_color	"#50FA7B"

bspc rule -a "*" split_dir=east
bspc rule -a Firefox desktop='^1' focus=on follow=on
bspc rule -a Firefox-esr desktop='^1' focus=on follow=on
bspc rule -a Vivaldi-stable desktop='^1' focus=on follow=on
bspc rule -a Alacritty desktop='^2' focus=on follow=on
bspc rule -a kitty desktop='^2' focus=on follow=on
bspc rule -a TelegramDesktop desktop='^5' 
bspc rule -a Spotify desktop='^7' 
bspc rule -a vlc desktop='^8' focus=on follow=on 
bspc rule -a DesktopEditors desktop='^4' focus=on follow=on 
bspc rule -a obsidian desktop='^4' focus=on follow=on 
bspc rule -a Virt-manager desktop='^6' focus=on follow=on 
bspc rule -a qimgv state=floating center=true
bspc rule -a Xarchiver state=floating layer=normal center=true
bspc rule -a mpv state=floating layer=normal center=true
bspc rule -a Pavucontrol:pavucontrol state=floating 
bspc rule -a Lxappearance state=floating layer=normal center=true
bspc rule -a Galculator state=floating layer=normal center=true
bspc rule -a Xfce4-terminal state=floating layer=normal center=true
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Inkscape desktop='^8' follow=on
bspc rule -a obs desktop='^9' follow=on
bspc rule -a discord desktop='^5' follow=on
bspc rule -a Thunar desktop='^3' follow=on
# bspc rule -a Geany desktop='^4' follow=on

dunst &
picom --config ~/.config/picom/picom.conf &
# feh --bg-fill ~/Wallpapers/wp2437910-ultrawide-wallpapers.jpg &
feh --randomize --bg-fill ~/Wallpapers/* &
# feh --bg-fill ~/Wallpapers/desktop-20.12.15090704-by-@WALLSBYJFL.jpg &
# feh --bg-fill ~/.config/backgrounds/wallhaven-y8o51x_3440x1440.png 
#
## Polybar or tint
~/bin/polybar-launch &
# tint2 &

## Clipmemu start
clipmenud &

## apps for systray if enabled
 # volumeicon &
 # nm-applet &
sxhkd &

# Set wallpaper
# nitrogen --restore &

telegram-desktop &


